default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USERNAME"]%>
  password: <%= ENV["DB_PASSWORD"]%>
  pool: 5

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
  username: blog
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
